### ISSUE TITLE
Having trouble initializing the library

### ISSUE THREAD

**Issue by askdesigners** [urbanze/esp32-wifi#3]
I've tried many variations at this point, but keep running into this error when compiling.
`undefined reference to 'WF::sta_connect(char const*, char const*)'`

I'm using the lib as described in the readme, and sort of lost as to why it's failing. Any ideas?

This is in my code
```
  WF wifi;
  wifi.sta_connect("networkname", "password");
```

I'm including the header file as normal `#include "wifi.h"` and the file is in the same DIR as my code. 
I'm using the official ESP IDF extension for VSCode, so no Arduino IDE or libraries. Do I need to change any settings to get it working?

**Comment by urbanze** [comment]
your main file is .c or .cpp?

Try to include wifi.cpp file too, can work!

**Comment by askdesigners** [comment]
Hi! Yes this is in a .cpp file. Actually it looks like the underlying API that this lib is built on has changed a lot, and might not work any more, which is a bummer. Lots of deprecation warnings... 

So you suggest to include not only the headerfile, but also the .cpp file as well?

I see that this lib is built mainly off of the examples from the IDF project, but in the later versions things have changed a good deal, and some framework methods are now deprecated, or have different argument expectations.

**Comment by urbanze** [comment]
@askdesigners Which version of ESP-IDF are you using? This lib is build to work in IDF 4.0

Today, many users frequently use IDF 4.2 in many project and this lib need to be updated manually to work.

I can update to 4.2

**Comment by askdesigners** [comment]
Ya I'm on 4.2 
If it's not a hassle to update I'd really appreciate it!
